---
title: "Value Added in China's Exports Showcase Domestic Industry, Changing Alliances"
author: "Michelle Tinker"
institute: "American University"
date: today
format: 
  pdf:
    include-in-header:
      text: |
        \usepackage{float}
        \floatplacement{figure}{H}
        \floatplacement{table}{H}
        \usepackage{indentfirst}
        \setlength{\parindent}{2em}
knitr:
  opts_chunk:
    echo: false
    eval: true
    prompt: false
    tidy: false
    comment: NA
    message: false
    warning: false
    fig.align: 'center'
    fig-asp: 0.618
---

\newpage 


# Value Added in Chinese Exports Signals Industrial Strength and Geopolitical Realignment 

&nbsp;Traditional trade statistics aren't always a good reflection of global value chains because they only reflect the trade in final goods and services and not intermediate parts and actions. The OCED Trade in Value (TiVA) database tries to address this issue by considering the value added by each country in the production of goods and services that are consumed worldwide. For example, if you have a car that is assembled in the United States and shipped to Canada to be sold in a Canadian dealership, traditional trade data would consider the value of the car as an export by the United States. However, the TiVA data takes into consideration the many times that car moves between Canada and Mexico as it is built before its final assembly. the TiVA data also considers the source of the parts that were used in the assembly of the car. The dollar value from parts and labor from Mexico is considered Mexico's "value added" in the United State's export of that car. 

&nbsp;In 2025, China recorded a record trade surplus of $1.19 trillion, in part because of its growing exports to the European Union, Africa, Latin America, and Southeast Asia. In the graph below I took a look at the foreign value added in China's exports as a percentage to see what countries have contributed to Chinese supply chains. I used the percentage of total value added rather than nominal figures to adjust for inflation and to identify broader geopolitical trends. The top 9 sources of value added in Chinese exports in 2022 were the United States, Chinese Taipei, South Korea, Japan, Australia, Russia, Saudi Arabia, Germany, and the category for the rest of the world. The OECD data only looks at 80 countries and has a 'rest of world' category for the remainder of the world's countries. The largest contributor to China's exports is China itself - The total amount of foreign value added in Chinese exports peaked at about 25 percent in 2004 and has since decreased to about 17 percent in 2022. As such, in 2022, 83 percent of the value in Chinese exports originated in China, which suggests that China's domestic industry remains quite strong.  

&nbsp;The data below illustrates that no single country accounts for more than five percent of value added in Chinese exports, underscoring China's strategic effort to avoid over-reliance on any individual partner. The makeup of this foreign value add has changed over the past two decades, with the value add of regional partners like Japan and South Korea decreasing over time and the value add of more recent geopolitical partners like Russia increasing. The United States has been one of China's top sources of value add in its exports over the past two decades, and although the total percentage of value add has decreased slightly since 2000, it remains quite high. This suggests that there is market value for US companies in China's exports. 
  

```{r}
#| fig-align: center

library(tidyverse)

exports <- read_csv("OECD.STI.PIE.DSD_TIVA_EXGRVA.csv")


# filtering the data for only value add to Chinese exports 
china_exports <- 
  exports |>
  filter(EXPORTING_AREA == "CHN")

regional_groups <- c("OECD", "WXOECD", "APEC", "ASEAN", "S2", "EU27_2020", 
                     "EU28", "EU15", "EU28XEU15", "EA19", "G20", "E", "S2_S8", 
                     "NAFTA", "A5_A7", "F", "W", "D", "W_O")  

china_exports_countries <- 
  china_exports |>
    filter(!VALUE_ADDED_SOURCE_AREA %in% regional_groups)

# getting the percentages 
china_exports_countries2 <- 
  china_exports_countries |>
  group_by(TIME_PERIOD) |>
  mutate(
    total_value = sum(OBS_VALUE, na.rm = T),
    percent_OBS = (OBS_VALUE / total_value) 
  ) |>
  ungroup() 

total_foreign <- 
  china_exports_countries2 |>
  filter(VALUE_ADDED_SOURCE_AREA != "CHN") |>
  group_by(TIME_PERIOD) |>
  summarise(
    VALUE_ADDED_SOURCE_AREA = "total_foreign",
    percent_OBS = sum(percent_OBS, na.rm = TRUE)
  ) |>
  ungroup()

#getting the top 10
top10 <- 
  china_exports_countries2 |>
    filter(TIME_PERIOD == 2022) |>
      arrange(desc(OBS_VALUE)) |>
        slice_head(n = 10)  

top10countries <- c("WXD", "USA", "TWN", "KOR", "JPN", "AUS", "RUS", 
                    "SAU", "DEU")

china_exports_top10 <- 
  china_exports_countries2 |>
    filter(VALUE_ADDED_SOURCE_AREA %in% top10countries)

china_exports_top10 <- 
  china_exports_top10 |>
    filter(between(TIME_PERIOD, 2000, 2022))

# Graphing the data --------------------------------------------
china_exports_top10 <- 
  china_exports_top10 |>
  mutate(source_area2 = VALUE_ADDED_SOURCE_AREA)  

countries <- as_labeller(c(`WXD` = 'Rest of World',
               `USA` = 'United States', 
               `TWN` = 'Chinese Taipei',
               `KOR` = 'South Korea', 
               `JPN` = 'Japan', 
               `AUS` = 'Australia', 
               `RUS` = 'Russia', 
               `SAU` = 'Saudi Arabia', 
               `DEU` = 'Germany'))

china_exports_top10 |>
  ggplot(aes(x = TIME_PERIOD, y = percent_OBS)) +
    geom_line(data = china_exports_top10 |> dplyr::select(-VALUE_ADDED_SOURCE_AREA), 
              aes(group = source_area2), color="grey", linewidth=0.5, alpha=0.5) + 
    geom_line(aes(color = VALUE_ADDED_SOURCE_AREA), linewidth=1.2) +
    scale_color_viridis_d() +
    scale_y_continuous(labels = scales::percent) +
    labs(
      x = 'Year',  
      y = 'Value Added', 
      caption = 'Source: OECD TiVA Database' 
    ) +
    theme_minimal() +
    theme(
      legend.position="none",
      plot.title = element_text(size=16, face = 'bold'),
      panel.grid = element_blank(), 
      axis.title=element_text(size=12,face="bold")
    ) +
    ggtitle("The Value Add in Chinese Exports") +
    facet_wrap(~VALUE_ADDED_SOURCE_AREA, labeller = countries)


```

# Works Cited 
Bradsher, Keith. 2026. “China Announces Record Trade Surplus as Its Exports 
   Flood World Markets.” The New York Times, January 14, 2026. https://www.    
   nytimes.com/2026/01/13/business/china-trade-surplus-exports.html.

Healy, Yan Holtz and Conor. n.d. “The Spaghetti Plot.” Www.data-To-Viz.com.   
   https://www.data-to-viz.com/caveat/spaghetti.html.

OECD. 2023. “Trade in Value-Added.” OECD. 2023. https://www.oecd.org/en/topics/   
   sub-issues/trade-in-value-added.html.

       

